# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Pace Maker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pace Maker
  # for HTTP method
  # pod 'Alamofire', '~> 5.2'

  # for GPX formatting
  pod 'CoreGPX'

  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
end

# add the Firebase pod for Google Analytics
# pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Firebase/Storage'

pod 'Firebase/Database'
