# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Pace Maker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 
  pod 'Charts'

  # for GPX formatting
  pod 'CoreGPX'

  # for Firebase Storage / realtime Database
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
end

